name: Build PDF
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix permissions before build
        run: |
          sudo chown -R 1000:1000 ${{ github.workspace }}

      - name: Build PDF in devcontainer
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/happi/thebeambook-devcontainer:latest
          options: |
            --user builder
            -v ${{ github.workspace }}:/workspaces/theBeamBook
            -w /workspaces/theBeamBook
          run: |
            make
            mv beam-book-a4.pdf beam-book.pdf
            ls -al *.pdf

      - name: Release PDF
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            beam-book.pdf
